-- New patterns pulled from latest Feb 20, 2026 web research on AI model advances, enterprise agentic systems, and synthetic intelligence.

INSERT INTO patterns (pattern, response, domain, metadata) VALUES
('Gemini 3.1 Pro Release', 'Google released Gemini 3.1 Pro with advanced reasoning capabilities, achieving 77.1% on ARC-AGI-2 and double the reasoning performance of Gemini 3 Pro.', 'ai_models', '{"company": "Google", "model": "Gemini 3.1 Pro", "benchmark": "ARC-AGI-2", "score": 77.1}'),
('Gemini 3.1 Multimodal Improvement', 'New Gemini model demonstrates improved spatial relationship understanding, shape mapping, and visual problem-solving capabilities.', 'ai_models', '{"company": "Google", "feature": "multimodal", "improvements": ["spatial", "visual", "shape_mapping"]}'),
('Infosys Anthropic Collaboration', 'Strategic partnership integrating Claude models with Infosys Topaz to automate complex workflows in regulated industries.', 'enterprise_ai', '{"partners": ["Infosys", "Anthropic"], "focus": "regulated_industries", "models": ["Claude", "Claude Code"]}'),
('Agentic AI for Regulated Industries', 'Enterprise agentic solutions combining governance and transparency for telecommunications, financial services, manufacturing, and software development.', 'enterprise_ai', '{"sectors": ["telecom", "finance", "manufacturing", "software"], "requirement": "regulatory_compliance"}'),
('Digital Workforce Davies Partnership', 'Strategic collaboration to bring agentic AI solutions to insurance and regulated industries.', 'enterprise_ai', '{"partners": ["Digital Workforce", "Davies"], "sector": "insurance", "focus": "regulated_markets"}'),
('Qwen3.5 Agentic Capabilities', 'Alibaba Qwen3.5 with 397B parameters supports new coding and agentic capabilities, compatible with open-source AI agents.', 'ai_models', '{"company": "Alibaba", "model": "Qwen3.5", "parameters": "397B", "feature": "agentic_compatibility"}'),
('China AI Agent Competition', 'ByteDance and Zhipu AI released upgraded models supporting agent capabilities, intensifying Chinese AI agent race.', 'agentic_ai', '{"region": "China", "competitors": ["ByteDance", "Zhipu AI"], "trend": "agent_capabilities"}'),
('Expedia Agentic AI Threat', 'Expedia annual report identifies agentic AI as major competitive threat, noting risks from AI-driven competitors and data scraping vulnerabilities.', 'business_ai', '{"company": "Expedia", "threat": "agentic_competition", "risks": ["competitors", "data_scraping", "liability"]}'),
('Agentic Commerce UCP Standard', 'Universal Commerce Protocol standardizes business connections with AI agents across shopping journey including secure digital identity.', 'agentic_ai', '{"standard": "UCP", "use": "commerce_automation", "features": ["identity", "transaction_flow"]}'),
('Cogent Security AI Vulnerability Agents', 'Raised $42M Series A to develop autonomous AI agents for vulnerability remediation in enterprise security.', 'security', '{"company": "Cogent Security", "funding": "$42M", "focus": "autonomous_vulnerability_remediation"}');
