-- New patterns pulled from latest Feb 22, 2026 web research on synthetic intelligence, robotics, and emerging AI developments.

INSERT INTO patterns (pattern, response, domain, metadata) VALUES
('Claude Code Security Launch', 'Anthropic launched Claude Code Security, an AI-powered vulnerability scanning feature that reasons through codebases like a human security researcher, tracing data flows and flagging vulnerabilities missed by rule-based tools.', 'ai_security', '{"company": "Anthropic", "product": "Claude Code Security", "capability": "vulnerability_scanning", "approach": "reasoning_based"}'),
('India AI Summit Declaration', '88 countries and regions including US, UK, and EU endorsed India-led AI declaration recognizing security importance but lacking binding safety measures, emphasizing democratization and wide-scale AI adoption.', 'ai_policy', '{"event": "AI Impact Summit", "location": "New Delhi", "signatories": 88, "focus": "democratization"}'),
('Gemini 3.1 Pro Release', 'Google released Gemini 3.1 Pro on February 20, 2026, featuring advanced reasoning for complex multi-step tasks with 77.1% on ARC-AGI-2 benchmark and doubled reasoning performance over Gemini 3 Pro.', 'ai_models', '{"company": "Google", "model": "Gemini 3.1 Pro", "benchmark": "ARC-AGI-2", "score": "77.1%", "features": ["reasoning", "code_generation", "multimodal"]}'),
('China Humanoid Spring Festival', 'Unitree Robotics humanoid robots performed coordinated kung-fu choreography and back-flips at Chinas Spring Festival Gala, demonstrating significant advances in agility and fault recovery over previous year.', 'robotics', '{"company": "Unitree Robotics", "event": "Spring Festival Gala", "country": "China", "activities": ["kung_fu", "backflips", "parkour"]}'),
('Tesla Optimus Production Shift', 'Tesla discontinued Model S and Model X to allocate factory space for Optimus humanoid robot production, redefining company identity from car manufacturer to AI robotics platform.', 'robotics', '{"company": "Tesla", "product": "Optimus", "pivot": "automotive_to_robotics", "market_share_target": "humanoids"}'),
('Toyota Agility Robot Deployment', 'Toyota Motor Manufacturing Canada deployed seven Agility Digit humanoid robots under robots-as-a-service deal after year-long pilot, marking significant factory automation milestone.', 'robotics', '{"company": "Toyota", "partner": "Agility", "robots": 7, "model": "Digit", "location": "Canada", "model": "RaaS"}'),
('Robot Hand Dexterity Breakthrough', 'Robot hand achieved human-like dexterity using visual-tactile training with only webcam and basic sensors, successfully performing both familiar and novel manipulation tasks.', 'robotics', '{"capability": "dexterity", "approach": "visual_tactile_training", "hardware": "webcam_sensors", "result": "human_like"}'),
('Amodei AI Jobs Warning Update', 'Anthropic CEO Dario Amodei reinforced warning that AI could eliminate half of entry-level white-collar jobs within five years, advocating for accountability and safety-first development.', 'ai_economics', '{"person": "Dario Amodei", "company": "Anthropic", "prediction": "50% entry_jobs", "timeline": "5_years", "solutions": ["constitutional_AI", "interpretability"]}'),
('MIT AI Agent Safety Index', 'MIT researchers cataloged 67 deployed agentic AI systems and found developers provide limited safety evaluations and testing disclosures despite increasing autonomy.', 'ai_safety', '{"institution": "MIT", "study": "AI Agent Index", "systems_cataloged": 67, "finding": "limited_safety_disclosure"}'),
('Biosecurity Data Framework', 'Over 100 researchers endorsed framework to govern sensitive biological data like health records, addressing risks of AI models trained on DNA creating bioweapons.', 'ai_safety', '{"researchers": 100, "focus": "biological_data_governance", "risk": "bioweapons", "initiative": "Genesis_Mission"}'),
('Meta AR Glasses Facial Recognition', 'Meta testing facial-recognition features on smart glasses hardware, raising privacy concerns as AR glasses proliferate in consumer market.', 'ai_privacy', '{"company": "Meta", "product": "smart_glasses", "feature": "facial_recognition", "concern": "privacy"}'),
('OpenAI Law Enforcement Debate', 'OpenAI debated calling police about suspected Canadian mass shooter ChatGPT chats flagged by misuse monitoring tools, raising questions about AI company responsibilities.', 'ai_ethics', '{"company": "OpenAI", "incident": "Canadian_shooter", "issue": "law_enforcement_reporting", "tool": "misuse_monitoring"}'),
('Generative AI Medical Research', 'UC San Francisco and Wayne State University found generative AI can process medical datasets faster than human research teams and produce stronger results in DREAM challenges.', 'ai_healthcare', '{"institutions": ["UCSF", "Wayne State"], "benchmark": "DREAM_challenges", "finding": "faster_stronger_results"}'),
('AI Ransomware Acceleration', 'Securin 2025 Ransomware Report found generative AI accelerating ransomware operations by lowering barriers and intensifying pressure, but not fully automating attacks.', 'ai_security', '{"company": "Securin", "report": "2025 Ransomware Report", "impact": "acceleration_not_automation", "effects": ["lower_barriers", "increased_scale"]}'),
('AI Company Lobbying Surge', 'OpenAI and Anthropic significantly increased lobbying efforts in 2025, focusing on national security and AI infrastructure while facing criticism for avoiding meaningful regulation.', 'ai_policy', '{"companies": ["OpenAI", "Anthropic"], "focus": ["national_security", "infrastructure"], "criticism": "regulation_avoidance"}'),
('China Humanoid Market Dominance', 'China accounts for over 85% of roughly 15,000 humanoid robot installations in 2025, up from 13% US share, with companies like Unitree offering base models at $13,500.', 'robotics', '{"country": "China", "market_share": "85%", "installations": 15000, "year": 2025, "price_example": "$13,500"}'),
('Alibaba RynnBrain Open Source', 'Alibaba open-sourced RynnBrain, a robotics foundation model designed for robots to perceive and understand 3D space, accelerating Chinese robotics AI capabilities.', 'robotics', '{"company": "Alibaba", "model": "RynnBrain", "type": "robotics_foundation_model", "capability": "3D_perception", "license": "open_source"}'),
('AI Boom Public Backlash', 'NYT reports significant public resistance to AI adoption with over third of survey respondents concerned AI could end human life, as tech leaders push forward with development.', 'ai_society', '{"source": "NYT", "concern_level": "33% existential", "issue": "public_resistance", "contrast": "industry_optimism"}');
