-- New patterns pulled from latest Jan 24, 2026 web research on agentic AI design patterns, advanced prompt engineering, and self-improving AI techniques.[^1][^2][^3][^4][^5][^6][^7]

INSERT INTO patterns (pattern, response, domain, metadata) VALUES
('ReWOO Pattern', 'Separate planning from execution: Use external planner to decompose tasks into tool calls, then execute separately for higher tool accuracy and reliability.', 'agentic_ai', '{"pattern": "ReWOO", "benefit": "tool_accuracy", "source": "2026_agentic"}'),
('CodeAct Pattern', 'Generate code snippets dynamically and execute them within the agent loop to solve computational or programmatic tasks.', 'agentic_ai', '{"method": "code_execution", "use_case": "coding_agents", "trend": "2026"}'),
('Context Budget Management', 'Implement strict token budgets per agent with parent-child inheritance and automatic summarization to avoid context exhaustion.', 'agentic_ai', '{"principle": "context_budget", "safety": "exhaustion_prevention", "enterprise": "true"}'),
('Agent Teams Coordination', 'Orchestrate teams of specialized agents where a coordinator delegates subtasks and synthesizes outputs for complex goals.', 'agentic_ai', '{"architecture": "multi_agent_team", "scale": "high", "collaboration": "coordinated"}'),
('Long-Running Persistent Agents', 'Maintain state and memory across extended sessions allowing agents to build complete systems or projects over time.', 'agentic_ai', '{"capability": "persistence", "application": "full_projects", "future": "2026_standard"}'),
('PromptCoT 2.0 Synthesis', 'Employ expectation-maximization loops to generate diverse, challenging synthetic prompts with rationales for reasoning improvement.', 'prompt_engineering', '{"framework": "PromptCoT_2.0", "scaling": "reasoning", "self_improving": "prompts"}'),
('CELI Framework', 'Embed structured control logic and decision trees directly into prompts for autonomous multi-stage workflow execution.', 'prompt_engineering', '{"innovation": "controller_embedded", "autonomy": "multi_stage", "integration": "tools"}'),
('Recursive Self-Improvement RSI', 'Enable AI to iteratively redesign its own prompts, tools, or architecture using verifiable self-generated feedback loops.', 'self_improvement', '{"method": "RSI", "acceleration": "exponential", "risk_level": "high"}'),
('Model Context Protocol MCP', 'Standardize structured context passing between LLMs, tools, and agents to ensure reliable multi-model interactions.', 'agentic_ai', '{"protocol": "MCP", "standard": "emerging_2026", "compatibility": "multi_provider"}'),
('Self-Play Agent Training', 'Agents autonomously play against themselves with feedback to evolve skills without external labeled data.', 'self_improvement', '{"training": "self_play", "data_efficient": "true", "autonomy": "full"}'),
('Multimodal Context Engineering', 'Combine text, vision, and audio modalities in dynamic prompts to handle richer, real-world task contexts.', 'prompt_engineering', '{"multimodal": "integrated", "trend": "2026_core", "enhancement": "context_rich"}'),
('EvoCUA Evolution', 'Evolve computer-use agents through massive scalable synthetic experiences mimicking real user interactions.', 'agentic_ai', '{"evolution": "synthetic_experience", "domain": "computer_use", "scale": "massive"}');
