-- New patterns pulled from latest Feb 19, 2026 web research on agentic AI, security vulnerabilities, synthetic intelligence, and neuromorphic computing.

INSERT INTO patterns (pattern, response, domain, metadata) VALUES
('OpenClaw SSRF Vulnerability', 'High severity CVE-2026-26322 affects OpenClaw Gateway tool with Server-Side Request Forgery allowing attackers to access internal systems.', 'security', '{"cve": "CVE-2026-26322", "severity": "high", "cvss": 7.6, "vendor": "OpenClaw"}'),
('OpenClaw Multiple Vulnerabilities', 'Endor Labs discovered six vulnerabilities in OpenClaw agentic AI assistant including SSRF, missing authentication, and path traversal bugs.', 'security', '{"count": 6, "types": ["SSRF", "auth_bypass", "path_traversal"], "vendor": "OpenClaw"}'),
('BrowserPod Secure Sandbox', 'Leaning Technologies launched BrowserPod for Node.js, a secure browser-based code execution sandbox for AI agents using WebAssembly.', 'agentic_ai', '{"company": "Leaning Technologies", "use": "secure_code_execution", "tech": "WebAssembly"}'),
('AI Billion Record Data Leak', 'Massive unsecured database exposed over 1 billion IDs, emails, and phone numbers linked to AI-powered identity verification service across 26 countries.', 'security', '{"impact": "data_breach", "records": "1B+", "countries": 26}'),
('AI Video App Data Exposure', 'Video AI Art Generator app leaked millions of user-generated images and videos due to misconfigured cloud storage bucket.', 'security', '{"type": "cloud_misconfig", "files": "2M+", "platform": "Google Play"}'),
('DeepRare AI Rare Disease Diagnosis', 'Agentic system for rare disease diagnosis combining clinical, genetic, and phenotypic data with traceable reasoning for clinicians.', 'medical_ai', '{"name": "DeepRare AI", "use": "rare_disease_diagnosis", "feature": "traceable_reasoning"}'),
('Copilot Grok C2 Proxy Attack', 'Security researchers demonstrated AI assistants with web browsing can be abused as malware command-and-control relays using crafted prompts.', 'security', '{"threat": "C2_abuse", "vectors": ["Copilot", "Grok"], "risk": "stealth_communication"}'),
('API Threat AI Blast Radius', 'AI-driven systems expand API attack blast radius, enabling machine-speed abuse and amplifying security impact exponentially.', 'security', '{"trend": "api_threat_growth", "driver": "AI", "impact": "amplified"}'),
('Neuromorphic PDE Solver', 'Sandia Labs algorithm enables neuromorphic hardware to solve partial differential equations for physics simulations at fraction of energy cost.', 'neuromorphic', '{"org": "Sandia Labs", "capability": "PDE_solving", "benefit": "energy_efficient"}'),
('Atom-Sized Neuromorphic Gates', 'Scientists created ultra-small pores rivaling biological ion channels for potential neuromorphic computing and DNA sequencing applications.', 'neuromorphic', '{"breakthrough": "nano_pores", "applications": ["neuromorphic", "DNA_sequencing"], "scale": "atomic"}');
